import {g4Uuid,g4Bundle,g4StudentRevision,g4ReviewCheck,g4Blockers} from './g4-domain.mjs';
import {g4CompleteFields,g4Document} from './g4-document.mjs';
export function createG4({sql,storage,reply,jsonColumn,model,clock=()=>Date.now()}){
 const bucket='career-prep-private',now=()=>new Date(clock()).toISOString(),sha=async b=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',b))].map(x=>x.toString(16).padStart(2,'0')).join('');
 const safeError=e=>String(e).replace(/^Error: /,'').slice(0,120);
 async function readDraft(owner,id){if(!g4Uuid(id))return null;const [d]=await sql`select * from career_prep.material_drafts where owner_id=${owner} and id=${id}`;return d?{...d,bundle:jsonColumn(d.bundle)}:null;}
 async function readVersion(owner,id){if(!g4Uuid(id))return null;const [v]=await sql`select * from career_prep.material_versions where owner_id=${owner} and id=${id}`;return v?{...v,content:jsonColumn(v.content)}:null;}
 async function storeVersion(owner,draft,content,version,requestId,deadline){
  const id=crypto.randomUUID(),created=now(),bytes=await g4Document(content,draft.bundle,{draft_id:draft.id,version,created_at:created}),sum=await sha(bytes),extension=draft.artifact_type==='interview_cards'?'json':'docx',path=`${owner}/materials/${draft.id}/${id}.${extension}`;
  if(bytes.length>5000000||clock()>=deadline)throw Error('MATERIAL_LIMIT_OR_DEADLINE');
  const type=extension==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/json';
  const upload=await storage.from(bucket).upload(path,bytes,{contentType:type,upsert:false});if(upload.error)throw Error('MATERIAL_UPLOAD_FAILED_OR_UNKNOWN');
  const check=await storage.from(bucket).download(path);if(check.error||await sha(new Uint8Array(await check.data.arrayBuffer()))!==sum)throw Error('MATERIAL_READBACK_FAILED');
  if(clock()>=deadline)throw Error('MATERIAL_SAVE_DEADLINE');
  await sql.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtext(${owner}))`;const [current]=await tx`select latest_version from career_prep.material_drafts where owner_id=${owner} and id=${draft.id} for update`;if(!current||current.latest_version!==version-1)throw Error('DRAFT_VERSION_CHANGED');await tx`insert into career_prep.material_versions(id,owner_id,draft_id,version_number,request_id,content,storage_path,sha256_hex,byte_count,origin) values(${id},${owner},${draft.id},${version},${requestId},${JSON.stringify(content)}::text::jsonb,${path},${sum},${bytes.length},${content.origin})`;await tx`update career_prep.material_drafts set latest_version=${version},status='awaiting_review',handoff='Review this exact version, complete placeholders and decide its intended use.' where owner_id=${owner} and id=${draft.id}`;});
  const saved=await readVersion(owner,id);if(!saved||saved.sha256_hex!==sum)throw Error('MATERIAL_RECORD_UNVERIFIED');
  return {id,version_number:version,sha256:sum};
 }
 async function prepare(owner,run,s){
  const deadline=clock()+90000,id=crypto.randomUUID();let draft,bundle;const c=s.results?.[0];
  try{bundle=g4Bundle(s);const [old]=await sql`select id,status,latest_version from career_prep.material_drafts where owner_id=${owner} and run_id=${run.id}`;if(old)throw Error('EXISTING_PREPARATION_INSPECT_FIRST');
   const [row]=await sql`insert into career_prep.material_drafts(id,owner_id,run_id,opportunity_id,artifact_type,data_mode,bundle,status,review_due_at) values(${id},${owner},${run.id},${bundle.opportunity_id},${bundle.artifact_type},${s.mode},${JSON.stringify(bundle)}::text::jsonb,'generating',case extract(isodow from now()) when 4 then now()+interval '4 days' when 5 then now()+interval '4 days' when 6 then now()+interval '3 days' else now()+interval '2 days' end) returning *`;draft={...row,bundle};
   s.preparation_calls=1;const raw=await model.generate(bundle,s.mode,deadline),content=g4CompleteFields(raw,bundle.artifact_type),version=await storeVersion(owner,draft,content,1,s.preparation_request.request_id,deadline);
   c.preparation={status:'prepared_for_review',draft_id:id,version_id:version.id,version:1,artifact_type:bundle.artifact_type,review_status:'awaiting_review',handoff:'Review your saved draft on Preparation. No material has been approved or sent.'};
  }catch(e){const reason=safeError(e),inputBlocked=!s.incomplete&&!draft&&/REQUIRES|REQUIRED|NOT_FOUND/.test(reason);c.preparation={status:'unresolved',blocked_on:inputBlocked?'student_input':'operational_error',artifact_type:s.preparation_request.artifact_type,reason,handoff:/REQUIRES|REQUIRED|NOT_FOUND/.test(reason)?'Review the target, confirmed resume summary, assessment and recommendation before requesting preparation again.':'Preparation stopped. Inspect saved materials before making a new request; this request will not be retried.'};if(draft)await sql`update career_prep.material_drafts set status='unresolved',handoff=${reason} where owner_id=${owner} and id=${id}`;if(!inputBlocked)s.incomplete=true;else s.awaiting_preparation_input=true;s.issues.push('Preparation: '+reason);}
  s.stage='ledger';
 }
 async function list(owner){const started=clock();const drafts=await sql`select * from career_prep.material_drafts where owner_id=${owner} order by created_at desc limit 30`;const ids=drafts.map(d=>d.id),allVersions=ids.length?await sql`select id,draft_id,version_number,content,origin,created_at from career_prep.material_versions where owner_id=${owner} and draft_id=any(${ids}) order by version_number desc`:[],allReviews=ids.length?await sql`select draft_id,version_id,decision,intended_use,comments,created_at from career_prep.material_reviews where owner_id=${owner} and draft_id=any(${ids}) order by created_at desc`:[];const result=[];for(const d of drafts){const versions=allVersions.filter(v=>v.draft_id===d.id),reviews=allReviews.filter(r=>r.draft_id===d.id);const b=jsonColumn(d.bundle);result.push({id:d.id,run_id:d.run_id,opportunity_id:d.opportunity_id,artifact_type:d.artifact_type,mode:d.data_mode,status:d.status,handoff:d.handoff?.startsWith('MATERIAL_')?'Private storage did not confirm this draft. It remains unresolved. Inspect the storage issue before starting a new request.':d.handoff,latest_version:d.latest_version,review_due_at:d.review_due_at,role:b.posting.role,employer:b.posting.employer,posting_url:b.posting.url,resume_version:b.resume_version,posting_version:b.posting_version,evidence:b.refs,assessment:b.assessment,versions:versions.map(v=>({...v,content:jsonColumn(v.content),review:reviews.find(r=>r.version_id===v.id)||null}))});}if(clock()-started>=5000)return reply({ok:false,code:'REVIEW_READ_DEADLINE',message:'The saved materials could not be read within five seconds. Refresh to inspect them.'},503);return reply({ok:true,drafts:result,configured:model.configured});}
 async function edit(owner,p){const started=clock();if(!g4Uuid(p?.draftId)||!g4Uuid(p.versionId)||!g4Uuid(p.requestKey))return reply({ok:false,code:'EXACT_VERSION_REQUIRED'},422);try{const d=await readDraft(owner,p.draftId),v=await readVersion(owner,p.versionId);if(!d||!v||v.draft_id!==d.id||v.version_number!==d.latest_version)throw Error('DRAFT_VERSION_CHANGED');const [existing]=await sql`select id from career_prep.material_versions where owner_id=${owner} and request_id=${p.requestKey}`;if(existing)throw Error('REVISION_ALREADY_SAVED_INSPECT_FIRST');const content=g4StudentRevision(v.content,p),saved=await storeVersion(owner,d,content,v.version_number+1,p.requestKey,started+5000);if(clock()-started>=5000)throw Error('REVISION_SAVE_OUTCOME_UNCONFIRMED');return reply({ok:true,version:saved,message:'Your edits are saved as a new version awaiting review. Previous decisions remain linked only to their original versions.'});}catch(e){return reply({ok:false,code:safeError(e),message:'The revision could not be confirmed. Refresh saved materials before another action.'},409);}}
 async function review(owner,p){const started=clock();if(!g4Uuid(p?.draftId)||!g4Uuid(p.versionId)||!g4Uuid(p.requestKey))return reply({ok:false,code:'EXACT_REVIEW_VERSION_REQUIRED'},422);try{const d=await readDraft(owner,p.draftId),v=await readVersion(owner,p.versionId);if(!d||!v||v.draft_id!==d.id||v.version_number!==d.latest_version)throw Error('DRAFT_VERSION_CHANGED');g4ReviewCheck(v.content,p);const id=crypto.randomUUID(),attestation={factsConfirmed:p.factsConfirmed===true,placeholdersResolved:p.placeholdersResolved===true,unresolvedClaims:p.unresolvedClaims!==false};await sql.begin(async tx=>{await tx`select pg_advisory_xact_lock(hashtext(${owner}))`;const [current]=await tx`select latest_version from career_prep.material_drafts where owner_id=${owner} and id=${d.id} for update`;if(current.latest_version!==v.version_number)throw Error('DRAFT_VERSION_CHANGED');await tx`insert into career_prep.material_reviews(id,owner_id,draft_id,version_id,request_id,decision,intended_use,comments,attestation) values(${id},${owner},${d.id},${v.id},${p.requestKey},${p.decision},${p.intendedUse.trim()},${p.comments.trim()},${JSON.stringify(attestation)}::text::jsonb)`;});const [check]=await sql`select id,version_id,decision from career_prep.material_reviews where owner_id=${owner} and id=${id}`;if(!check||check.version_id!==v.id||check.decision!==p.decision||clock()-started>=5000)throw Error('REVIEW_WRITE_UNCONFIRMED');return reply({ok:true,message:`Your ${p.decision.replaceAll('_',' ')} decision is saved for version ${v.version_number}. No material was sent.`,review:check});}catch(e){return reply({ok:false,code:safeError(e),message:'Review was not confirmed. Resolve any placeholders and refresh the exact saved version before another decision.'},409);}}
 async function download(owner,p){if(!g4Uuid(p?.versionId))return reply({ok:false,code:'VERSION_NOT_FOUND'},404);const v=await readVersion(owner,p.versionId);if(!v)return reply({ok:false,code:'VERSION_NOT_FOUND'},404);const d=await readDraft(owner,v.draft_id),r=await storage.from(bucket).download(v.storage_path);if(r.error)return reply({ok:false,code:'MATERIAL_UNAVAILABLE'},503);const bytes=new Uint8Array(await r.data.arrayBuffer());if(await sha(bytes)!==v.sha256_hex)return reply({ok:false,code:'MATERIAL_INTEGRITY_FAILED'},503);let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return reply({ok:true,fileName:`${d.artifact_type}-v${v.version_number}.${d.artifact_type==='interview_cards'?'json':'docx'}`,base64:btoa(binary),sha256:v.sha256_hex});}
 return {prepare,configured:model.configured,list_preparation:list,save_material_revision:edit,record_student_review:review,download_material:download};
}
