import test from 'node:test';import assert from 'node:assert/strict';import {cleanupRequest,createOpportunityLibrary}from'../supabase/functions/_shared/opportunity-library.mjs';import worker from'../app/worker/index.mjs';
const id='op_'+ 'a'.repeat(24),other='op_'+'b'.repeat(24),request='00000000-0000-4000-8000-000000000001';
function harness(){let db={owners:{a:0,b:0},ledger:[{owner:'a',data_mode:'synthetic',opportunity_id:id,record:{posting:{role:'Analyst',employer:'Synthetic Co'}},version_number:1},{owner:'b',data_mode:'synthetic',opportunity_id:other,record:{},version_number:1}],visibility:[],history:[]};const queries=[];
 async function sql(p,...v){const q=p.join('?').replace(/\s+/g,' ');queries.push(q);if(q.includes('pg_advisory'))return[];
 if(q.startsWith('select opportunity_revision'))return[{opportunity_revision:db.owners[v[0]]}];
 if(q.startsWith('select action,selections'))return db.history.filter(x=>x.owner===v[0]&&x.request===v[1]);
 if(q.startsWith('select distinct on'))return db.ledger.filter(x=>x.owner===v[0]);
 if(q.startsWith('select distinct data_mode'))return db.ledger.filter(x=>x.owner===v[0]&&v[1].includes(x.opportunity_id));
 if(q.startsWith('select data_mode,opportunity_id,archived'))return db.visibility.filter(x=>x.owner===v[0]);
 if(q.startsWith('insert into career_prep.opportunity_visibility')){let x=db.visibility.find(x=>x.owner===v[0]&&x.data_mode===v[1]&&x.opportunity_id===v[2]);if(x)x.archived=v[3];else db.visibility.push({owner:v[0],data_mode:v[1],opportunity_id:v[2],archived:v[3]});return[];}
 if(q.startsWith('insert into career_prep.opportunity_cleanup_history')){db.history.push({owner:v[0],request:v[1],action:v[2],selections:JSON.parse(v[3]).map(x=>({id:x.id,mode:x.mode})),revision:v[4]});return[];}
 if(q.startsWith('update career_prep.owners')){db.owners[v[0]]++;return[];}throw Error(q);}
 sql.begin=async fn=>{const old=structuredClone(db);try{return await fn(sql);}catch(e){db=old;throw e;}};
 return{api:createOpportunityLibrary({sql,reply:(x,s=200)=>Response.json(x,{status:s}),jsonColumn:x=>typeof x==='string'?JSON.parse(x):x}),db:()=>db,queries};
}
const input=(extra={})=>({requestKey:request,action:'archive',confirmed:true,expectedRevision:0,items:[{mode:'synthetic',id}],...extra});
test('cleanup rejects malformed, duplicate, oversized, or unconfirmed selections',()=>{assert.equal(cleanupRequest(input({confirmed:false})),null);assert.equal(cleanupRequest(input({items:[{mode:'synthetic',id},{mode:'synthetic',id}]})),null);assert.equal(cleanupRequest(input({items:Array(501).fill({mode:'live',id})})),null);assert.ok(cleanupRequest(input()));});
test('archive persists, restores by new revision, preserves evidence, and deduplicates a repeated request',async()=>{const h=harness(),before=JSON.stringify(h.db().ledger);assert.equal((await h.api.update_opportunity_library('a',input())).status,200);assert.equal((await h.api.update_opportunity_library('a',input())).status,200);assert.equal(h.db().owners.a,1);assert.equal((await(await h.api.list_opportunity_library('a')).json()).items[0].archived,true);assert.equal((await h.api.update_opportunity_library('a',input({action:'restore',expectedRevision:1,requestKey:request.replace(/1$/,'2')}))).status,200);assert.equal((await(await h.api.list_opportunity_library('a')).json()).items[0].archived,false);assert.equal(JSON.stringify(h.db().ledger),before);assert.ok(h.queries.every(q=>!/(delete|truncate|drop)/i.test(q)));});
test('foreign IDs, mixed-owner selections, stale revisions, and wrong modes do not mutate another owner',async()=>{for(const patch of [{items:[{mode:'synthetic',id:other}]},{items:[{mode:'synthetic',id},{mode:'synthetic',id:other}]},{expectedRevision:5},{items:[{mode:'live',id}]}]){const h=harness();assert.equal((await h.api.update_opportunity_library('a',input(patch))).status,409);assert.equal(h.db().visibility.length,0);assert.equal(h.db().owners.b,0);}});
test('cleanup endpoints require sign-in and reject cross-origin writes',async()=>{for(const route of ['library','library/update']){assert.equal((await worker.fetch(new Request('https://example.test/api/g2/'+route,{method:'POST'}),{})).status,401);assert.equal((await worker.fetch(new Request('https://example.test/api/g2/'+route,{method:'POST',headers:{'oai-authenticated-user-email':'student@example.test','content-type':'application/json',origin:'https://other.test'},body:'{}'}),{G1_GATEWAY_SECRET:'fixture',SUPABASE_G1_URL:'https://fixture.test'})).status,403);}});
